# Generated by Django 2.1.7 on 2019-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('saddr', models.CharField(max_length=50)),
                ('sage', models.IntegerField()),
            ],
        ),
    ]
